import os
import sys
import resource
import glob
import subprocess
from datetime import datetime, timedelta
import pandas as pd

# Hardcap RAM usage to 4 GB (4 * 1024 * 1024 * 1024 bytes)
MAX_RAM_BYTES = 4 * 1024 * 1024 * 1024
try:
    resource.setrlimit(resource.RLIMIT_AS, (MAX_RAM_BYTES, MAX_RAM_BYTES))
except Exception:
    pass

def run_worker(start_str, end_str):
    # The actual data fetching is done in this worker subprocess
    from src.evaluation.argo_colloc import load_argo_argopy, collocate_to_grid
    print(f"  [Worker] Fetching {start_str} to {end_str}...")
    
    profiles = load_argo_argopy(
        lat_bounds=(5, 30), lon_bounds=(45, 105),
        start=start_str, end=end_str
    )
    
    if profiles.empty:
        print(f"  [Worker] No data found for {start_str} to {end_str}")
        return
        
    collocated = collocate_to_grid(profiles)
    out_name = f"data/processed/tmp_{start_str}_{end_str}.parquet"
    collocated.to_parquet(out_name)
    print(f"  [Worker] Saved {len(collocated)} observations to {out_name}")

def fetch_recursive(start_str, end_str):
    print(f"-> Attempting to fetch {start_str} to {end_str}...")
    
    # Call ourselves as a subprocess to isolate crashes/ABORTs
    cmd = [sys.executable, __file__, "worker", start_str, end_str]
    result = subprocess.run(cmd)
    
    if result.returncode == 0:
        return # Success!
        
    print(f"[!] Chunk {start_str} to {end_str} failed (exit code {result.returncode}). Splitting into smaller chunks...")
    
    # Split the date range in half
    start_dt = datetime.strptime(start_str, "%Y-%m-%d")
    end_dt = datetime.strptime(end_str, "%Y-%m-%d")
    delta = end_dt - start_dt
    
    if delta.days <= 1:
        print(f"[!] Cannot split {start_str} to {end_str} any further. Skipping.")
        return
        
    mid_dt = start_dt + delta / 2
    mid_str1 = mid_dt.strftime("%Y-%m-%d")
    mid_dt2 = mid_dt + timedelta(days=1)
    mid_str2 = mid_dt2.strftime("%Y-%m-%d")
    
    # Recursively fetch the two smaller halves
    fetch_recursive(start_str, mid_str1)
    fetch_recursive(mid_str2, end_str)

def main():
    # If launched with "worker", just run the fetch and exit
    if len(sys.argv) > 1 and sys.argv[1] == "worker":
        run_worker(sys.argv[2], sys.argv[3])
        return

    print("Fetching ARGO data with dynamic chunking and 4GB hardcap...")
    os.makedirs("data/processed", exist_ok=True)
    
    # Clear any old temp files from a previous run
    for f in glob.glob("data/processed/tmp_*.parquet"):
        os.remove(f)

    # Initial big chunks (quarters)
    quarters = [
        ("2023-01-01", "2023-03-31"),
        ("2023-04-01", "2023-06-30"),
        ("2023-07-01", "2023-09-30"),
        ("2023-10-01", "2023-12-31")
    ]
    
    for start, end in quarters:
        fetch_recursive(start, end)
        
    # Combine all temp files generated by the workers
    print("\nCombining all chunks...")
    tmp_files = sorted(glob.glob("data/processed/tmp_*.parquet"))
    
    if not tmp_files:
        print("No data was downloaded!")
        return
        
    dfs = [pd.read_parquet(f) for f in tmp_files]
    final_df = pd.concat(dfs, ignore_index=True)
    
    out_path = "data/processed/argo_collocated.parquet"
    final_df.to_parquet(out_path)
    
    # Cleanup temporary chunk files
    for f in tmp_files:
        os.remove(f)
        
    print(f"Done! Saved {len(final_df)} observations to {out_path}")

if __name__ == "__main__":
    main()
